name: task_master_ui
description: UI module contains ui components to bes used across project
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  top_snackbar_flutter: ^3.1.0
  utils:
    path: ../utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

