name: task_master_repo
description: Module that holds api repositories and api connection layer
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  meta: ^1.11.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  task_master_storage:
    path: ../../packages/task_master_storage
